# Makefile
# CMPS 111 Assignment 2
# Rogelio Molina-Marquez (rgmolina@ucsc.edu),
# Casey Chien (cdchien@ucsc.edu),
# Timothy Su (tisu@ucsc.edu)

Hello:	HelloWorldLoop.c
		cc -o Hello HelloWorldLoop.c
clean:
		rm -f Hello