# Makefile
# CMPS 111 Assignment 3
# Rogelio Molina-Marquez (rgmolina@ucsc.edu),
# Casey Chien (cdchien@ucsc.edu),
# Timothy Su (tisu@ucsc.edu)

all:	callocLoop.c
		cc -o loop callocLoop.c
clean:
		rm -f loop
